#!/bin/bash 
#### 
# Environment setting script. Automatically generated by Bake
####

echo "> Call with . bakeSetEnv.sh or source bakeSetEnv.sh"
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/binh/dce/build/lib
 export PATH=$PATH:/home/binh/dce/build/bin
 export PYTHONPATH=$PYTHONPATH:/home/binh/bake:/home/binh/dce/build/lib:/home/binh/dce/build/lib/python2.7/dist-packages
 export INSTALL_BASE=/home/binh/dce/build
